---
title: "lit_review"
output: html_document
---

# Berrone 2016

245 US communities across 7 years.

DV is community income inequality: gini index (a zero means all households have equal income). IVs were welfare nonprofit density (number of welfare nonprofits and their size), elite nonprofit density, and government envorcement capability (number of government enforcement actions like fines). Also considered things like demographic heterogeneity, racial diversity, and conservative political ideology.

They use a fixed-effects regression model to capture unobserved, time-invariant factors that affect community poverty (Wooldridge, 2012). They used a Hausman test to determine if a fixed or random effects model was more appropriate. 

They check lag one and lag two relationships of their main predictor on their DV.

Relationship between community income inequality and welfare nonprofit density, elite nonprofit density, and government enforcement (fines). They are arguing that community level things like demographic heterogeneity and diversity and government regulations influence the ability of nonprofits to diminish income inequality. So the relationship between income inequality and nonprofit density is the big dog, and then the other factors are demographic things and diversity things.

They say they have panel data, but they don't report how much.

## Dynamic notions:

unobserved heterogeneity (hausman test)
lags

## Opportunities:

Initial conditions
Memory
Timescales
Boundary Conditions
Reciprocal relationships
Equilibrium
Random Walks and White Noise
Stationarity
Endogeneity


# Call 2015

5 time point data spanning over 15 months. No discussion of data separation.

Measures: unit performance, turnover rate (not of the same people, just of that area), turnover rate change: subtracting previous quarters turnover rate from current rate. Quality of turnover was who left -- individual service orientation (individual difference measure) of each of the people who left. 

Their model regresses unit performance on prior turnover rate, turnover rate change, and other things.

Ran a Hausman test to determine if fixed or random effects are better (they found that the unique errors were not correlated with the regressors). 

## Dynamic notions:

Unobserved heterogeneity (hausman test)
Lags
Timescales
Serial Correlation

## Opportunities:

Initial conditions
Boundary Conditions
Reciprocal relationships
Equilibrium
Random Walks and White Noise
Stationarity
Endogeneity


# Drescher 2014

Teams played an online simulation game (Trivian, groups of 23 individuals), they waited until the teams got used to each other before collecting data. Then measured three times each separated by 8 weeks. 

Looked at autocorrelation, slopes, and changes in each variable over time. Correlated performance change and trust change with shared leadership.

## Dynamic notions

autocorrelation
lags

## Opportunities

Initial conditions
Timescales
Boundary Conditions
Reciprocal relationships
Equilibrium
Random Walks and White Noise
Stationarity
Endogeneity

# Gabriel diefendorff

Looking at emotions, surface acting, and deep acting on a momentary basis. Expecting them to fluctuate across time. In response to customer incivility, emotions become more negative and surface acting increaeses (within person). 

84 students in 90 minute call center simulation. Opening and closing script, but the remainder of their dialogue was left open to them. All confederates follow same script (the caller). Participants then listen back to the recording and rate continuous emotions and surface/deep acting. A couple of different conditions concerning recovery.

## Dynamic notions

Lags
Autocorrelation
Reciprocal relationships (although emphasized as "reverse causal paths" so really they are interested in a single t to t+1 rather than what it is across time)
Timescales

## Opportunities

Initial conditions
Boundary Conditions
Equilibrium
Random Walks and White Noise
Stationarity
Endogeneity

# Hardy 2018

SELF REGULATORY LEARNING

How cognitive, motivational, and behavioral regulatory processes conspire to promote or inhibit learning outcomes. 
Self regulation and learning are dynamic processes that occur at the within person level and unfold over time and across multiple levels of analysis. 
Examine the nature and directionality of interrelationships among commonly studied cognitive, motivational, and behavioral self-regulated learning variables in the context of a technology-mediated, learner controlled training environment. 
	- Self efficacy
	- Meta cognition
	- Exploratory behavior


Hypotheses
	- Prior self efficacy negatively related to subsequent exploratory behavior
	- Prior self efficacy negatively related to subsequent meta cognition
	- Prior exploratory behavior positively related to subsequent metacognition
	- Prior metacognition negatively related to subsequent exploratory behavior
	- Prior exploration positively related to subsequent self efficacy
	- Prior meta cognition positively related to subsequent self efficacy
Method
	- Lab students played a first person shooter game
	- 2 baseline trials
	- 20 3 minute practice trials for the practice learning phase
		○ Divided into five sessions
		○ After each session people responded to surveys
			§ Self efficacy
			§ Meta
			§ Goals
	- Exploratory behavior coded by people watching them play
	- Bivariate cross-lagged latent growth models
		○ Cross-lagged regression
			§ Teasing apart issues of directionality in relationships
		○ Latent growth modeling
			§ Modeling covariation between each repeated variable's latent intercept and growth terms, thus addresssing the potential confounding influences of slope covariation (i.e., spurious positive relationships that may emerge due to similarities in the trajectories of two variables). 
	- Compared 4 models
		○ Univariate latent growth (independence model)
		○ Unidirectional model (B to A)
		○ Unidirectional model (A to B)
		○ Bidirectional model
	- Trends in all variables except self efficacy 
No stationarity check

## Dynamic Notions

Lags
Reciprocal relationships

## Opportunities

Initial conditions
Memory
Timescales
Boundary Conditions
Equilibrium
Random Walks and White Noise
Unobserved heterogeneity
Stationarity
Endogeneity

# Jones et al., 2016

	• Method
		○ Pregnant participants
		○ Initial survey
			§ Demographics
			§ Perceived supervisor support
			§ Work family culture
		○ Weekly survey
			§ Identity management
				□ Revealing, concealing, and signaling pregnant behaviors
					® Concealing = hiding pregnancy
					® Revealing = revealing pregnancy
			§ Physical health symptoms
	• Findings
		○ Concealing = improved physical health
		○ Revealing reciprocal influence with physical health. Revealing = declines in physical health and declines in physical health = decreases in revealing.
		○ Women in supportive work contexts reported lower levels of concealing, higher levels of revealing, and less frequent physical health symptoms early. But these early benefits may be undermined via progressive decreases in concealing and increases in revealing, which lead to declines in physical health
	• Issues
		○ Stationarity?
		○ Intitial conditions?
		○ Reciprocal decrease forever?

## Dynamic notions

Reciprocal relationships
Lags
Autocorrelation
Memory

## Opportunities

Initial conditions
Timescales
Boundary conditions
Equilibrium
Random walks and white noise
Unobserved heterogeneity
Stationarity
Endogeneity

# Taylor et al., 2014

workplace incivility and its relationship to burnout, which leads to changes in turnover cognitions. Their hypotheses are consistent with a bivariate change model. Employees complete paper and pencil test every friday for 6 weeks. Used a latent change score model.

## Dynamic notions

Lags
Reciprocal relationships
Autocorrelation

## Opportunities

Initial conditions
Timescales
Boundary conditions
Equilibrium
Random walks and white noise
unobserved heterogeneity
stationarity
endogeneity

# Tepper 2018

Relationships between positive affect, transformational leadership, and transformational leadership need on behalf of the follower.

## Dynamic notions

Autoregression
Lags

## Opportunities

Initial conditions
Timescales
Boundary conditions
Equilibrium
Reciprocal relationships
Random walks and white noise
unobserved heterogeneity
stationarity
endogeneity


