---
title: "Meeting"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

# Take aways from last time

* Intro is about "everybody says dynamics" -- paper is now about taking a dynamic perspective.

# Today

1) Linear dynamic systems model

the basic y equation in matrix form. Our past research were subsumed in the general linear model. As we approach dynamics our investigations will be subsumed in this general model. This equation embodies the principles we discussed above, and it will be the core model of our dynamic investigations.

2) Highlight our opportunities and a mini lit review.

No extra data needed, they are doing great things and covering really cool principles.

3) Replace "system of equations" with dynamic systems

Put in 5 member teams, etc.

4) Cointegration after stationarity.

There are models that you can use to examine relationships that don't assume stationarity, these are called cointegration models.

5) Stationarity: equlibrium is the main concept. A system in equilibrium results in stationarity.

6) Ergodicity

when is it reasonable to pool? Homogeneity of dynamics

Unobserved heterogeneity is heterogenteity of unit effects, of individual differences. 

# Also

At the end: What dynamics is not

Don't put time as a moderator
Don't make a static box and arrow diagram

