---
# https://crsh.github.io/papaja_man/index.html

title             : "Principles For Taking a Dynamic Perspective"
shorttitle        : "DYNAMICS PRINCIPLES"

author: 
  - name          : "Christopher R. Dishop"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "316 Physics Rd, Psychology Building Room 348, East Lansing, MI 48823"
    email         : "dishopch@msu.edu"
    
  - name          : "Jeffrey Olenick"
    affiliation   : "1"

  - name          : "Richard. P DeShon"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "Michigan State University"


author_note: |
  ....

abstract: |
  Over the past two decades, researchers have become increasingly interested in dynamics. Longitudinal data structures are increasingly common and dynamic theories and hypotheses enter the literature every week. Despite more emphasis on dynamic relationships, researchers tend to discuss only a limited set of dynamic principles -- like lags -- or couch their thinking with respect to a specific statistical model -- like growth. Our field has without question benefited from studies turning to longitudinal data and exploring some dynamic ideas, but there are many more fundamental dynamic principles to consider. In this paper, we provide a host of dynamic principles to build consensus on what it means to take a dynamic perspective and provide new opportunities for resarchers to emphasize as we enter this domain. 
  
keywords          : "dynamic, dynamics, linear dynamic systems model, dynamic systems, longitudinal, process"
wordcount         : "95"

bibliography      : ["references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figs/',echo = FALSE, warning = FALSE, message = FALSE)
```


```{r child = 'pp_intro.Rmd'}
```

```{r child = 'pp_growth.Rmd'}
```

```{r child = 'pp_relationships.Rmd'}
```

```{r child = 'pp_dynamics.Rmd'}
```

```{r child = 'pp_concepts.Rmd'}
```

```{r child = 'pp_math.Rmd'}
```

```{r child = 'pp_modeling.Rmd'}
```

```{r child = 'pp_discussion.Rmd'}
```


\newpage

# References
```{r create_references}
r_refs(file = "references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}