---
output: pdf_document
---

## Concepts and Conventions

These first principles are concepts to help researchers think about dynamics.

### States

In organizational science we typically use the term "variable" to describe a measured construct and our lens is usually across people. Burnout, depletion, fatigue, OCBs, performance, job satisfaction -- these are all variables; they are quantities with values that fluctuate across people. When we instead focus on how those values fluctuate across time we call them "states." Performance as a variable, therefore, focuses on the set of values across people, whereas performance as a state focuses on its values across time. 

Researchers have indirectly called attention to the dynamic notion of states by distinguishing traits, or stable individual differences, from states. This distinction is prevalent in personality resarch [e.g., @dalal2015personality ;@hamaker2007integrated ], but also emerges in motivation [e.g., @beck2013state; @dragoni2005understanding] and emotion [e.g., @miner2010state] research, among others.

The convention to label states is to use what is called a state vector. A state vector for depletion, fatigue, and performance would be: (depletion, fatigue, performance) and its mathematical equivalent is, $(x_1, x_2, x_3)$ or $(x_1 ...x_n)$. We will use this notation later after introducing more concepts.

### Memory and Self-similarity

A fundamental concept in dynamics is that states often have memory -- they are self-similar across time. Individual, dyadic, and team performance may vary or fluctuate over time, but they retain self-similarity from one moment to the next. Job satisfaction now is some function of what it was just prior to now. My conscientiousness tomorrow will have carry over from what it was today, as will the number of people I communicate with. Researchers of course may argue that some states have no memory, but the point here is that states tend to retain something about what they are from moment to moment. 

### Constraints

When a state has memory or self-similarity it can still fluctuate or change over time -- to say that Rachel's job satisfaction will predict itself over time does not mean that we expect her job satisfaction to be identical every day. Instead, it will fluctuate or vary but under the constraints of where it was in the past. Imagine we argue that job satisfaction has no memory. If we grant that statement, then Rachel's job satisfaction from moment to moment is unconstrained and it can swing (potentially) to positive or negative infinity based the states that cause it. But if it does have memory then it is constrained, it cannot swing explosively. When she experiences something negative at work -- like ridicule -- her job satisfaction will certainly decrease in the moment, but what is her job satisfaction decreasing from? The answer is its prior level -- the negative experience is pushing against her prior level of job satisfaction, job satisfaction is not created from scratch just after ridicule. States vary over time, but where they go is constrained by their history.

It is also helpful to consider what would happen if we vary the strength of Rachel's job satisfaction memory. Imagine that her job satisfaction is only weakly self-similar. When she then experiences ridicule we would expect her satisfaction to fluctuate to a large extent, decreasing considerably with respect to the strength of the ridicule. When instead her satisfaction is strongly self-similar the ridicule would not lower it to the same degree.

### Lags

Memory is not limited to a single variable. Job satisfaction may also be influenced by the prior history of other states like, for example, autonomy, fatigue, and co-worker support. Imagine we believe that fatigue has a lag effect on performance, where the influence of fatigue on performance does not happen immediately but instead after some period of time. Despite collecting longitudinal data many researchers still examine concurrent relationships by regressing DVs on IVs at the same moment. That is, they regress performance at time four on fatigue at time four and performance at time six on fatigue at time six despite having the possibility to explore lag effects. What these concurrent models imply is that the researcher expects fatigue to instantaneously influence performance. With some states immediate cause makes sense, but as our "over time" thinking progresses there will be many opportunities to explore lags. 

### Reciprocal Influence

Many research questions can be boiled down to trying to find antecedents and outcomes, but when we focus on dynamics and start thinking about memory, constraints, and lags across multiple states we focus less on "true causes" or antecendents and more on reciprocal influence. This kind of thinking often takes the form, "and then this happens." Consider the (example) reciprocal relationships between performance, superior support, and fatigue. I perform my assignment well so my boss sends a nice email letting me know that she appreciates my work. Feeling inspired, I subsequently increase my performance and again perform well on my second assignment. Having increased my performance, however, I am now more fatigued and on my third assignment I perform poorly -- and this poor performance is not followed by another congratulatory email. In this simple example, performance, fatigue, and superior support fluctuate across time. We are not necessarily interested in finding the "true" cause, direction of effects, or the exact coefficient between one state and another, but instead the pattern of reciprocal relationships across time. 

### Timescales

Timescales are an important concept in systems with lags, memory, constraints, and reciprocal influence. Even within one phenomenon, effects can occur on different timescales. Consider the temperature of a building. The quick dynamics occur from room to room, where air molecules pass between rooms until all are roughly the same temperature. The exterior weather, conversely, influences the building under a different, delayed timescale. Heat confronts the exterior walls, warms them, and ultimately influences the entire building only after a much longer period of time than the interior air-flow. 

@mathieu2006clarifying provide another timescales example with respect to employee motivation. "Consider a work redesign effort intended to empower employees and thereby to enhance their work motivation with the aim of increasing customer satisfaction. How long does it take to establish the new work design? If employees are indeed more motivated to perform, how long will it take for customers to notice and for them to become more satisfied?" (p. 1035). Note that we are emphasizing the timescales of the underlying phenomena, not measurement timing. Measurement timing is of course an important issue but it has received attention elsewhere [@kenny1979correlation; @james1982causal].

### Boundary Space

When researchers estimate a growth curve and argue for a positive linear trend they are implying that the trajectory increases forever. Job satisfaction perpetually increases; OCBs go down endlessly. In dynamic systems with reciprocal influence and constraints, there are boundaries on where processes can go. Communication may fluctuate day to day, and it may even increase steadily as an employee transitions into a new role, but it is unlikely that it will continue to increase or decrease without bound forever. Estimating a quadratic term does not resolve this issue. A predicted quadratic line can appear to level-off, but it appears so because the prediction line is cut-off by the number of observed time points in the study -- a quadratic term implies a full U-shaped trajectory. 

### Initial Conditions

The last concept is that initial conditions may or may not influence the overall dynamics. Imagine an employee's climate perceptions fluctuating over time and showing a reciprocal pattern with a number of other important states. The dynamics of his climate perceptions may depend on his first encounters with the company -- his initial perceptions. Perhaps his initial perceptions were positive and over time showed reciprocal patterns with performance, dyadic social exchanges, burnout, and leadership perceptions. A researcher paying attention to initial conditions would examine if those same reciprocal patterns emerge under different starting conditions, like a bad first encounter.

An example is in @liebovitch2010dynamics explanation and model of conflict and cooperation between two actors. Their explanation involves three states in a two-person situation, including (1) each individual's general affective state, (2) feedback from one person to the other, and (3) each individual's general tendency to change based on the feedback. They argue that the patterns of conflict and cooperation that two individuals demonstrate over time differ dramatically if both individuals start with the same affective tone (positive and positive or negative and negative) versus opposing tones -- that is, the dynamics of conflict and cooperation are sensitive to the initial conditions of the actors involved. 

### Describing Trajectories

In this paper, we introduce concepts and statistical properties that merit attention as we approach dynamics. Readers should also see a paper by Monge (1990) that provides basic vocabulary for describing trajectories. He discusses terms like trend, periodicity, and cycles -- lexicon for patterns over time rather than key concepts that are emphasized here. We feel that his paper should be required reading for anyone interested in dynamics. 

