---
output: pdf_document
---

# Opening the Door to Dynamics

The point of highlighting the studies above was not to exhaustively review every instance of the word dynamic being used in research, but to sample common ways empirical researchers in applied psychology approach dynamics. Both frameworks are valuable, they move beyond cross-sectional research, address new and interesting questions, and consider great notions such as growth, relationship patterns over time, between and within-person variance comparisons, and inter-individual differences in intra-individual trend. But the concepts that receive majority attention are couched in specific statistical models and some, as we argue below, are actually not dynamics. When ideas are couched in a specific statistical model they miss other fundamental concepts and emphasize observed, manifest results rather than core notions about the phenomenon. Describing dynamics with manifest results from specific statistical models rather than fundamental concepts about the underlying process is like trying to convey how an engine works by only describing its temperature trend. Dynamics is a much broader concept with principles that describe and characterize processes over time that merit attention irresspective of the specific statistical model employed by the researcher. 

We provide a host of dynamic principles to create consensus on what it means to take a dynamic perspective. Some of the principles are concepts, ways of thinking that are necessary to appreciate as researchers and theorists explore dynamic phenomona. Others are statistical properties that arise when researchers apply models to longitudinal data structures -- they are statistical issues that produce inferential errors if left unchecked and they are important across all types of statistical models applied to panel data. The dynamic perspective that we present will benefit researchers by allowing them to better conceptualize, study, and convey the dynamic characteristics of the underlying process rather than an observed result such as trend. 

# Dynamics

Dynamics refers to a specific branch of mathematics/mechanics, but the term is used in different ways throughout our literature. It is used informally to mean "change", "fluctuating," "volatile," "longitudinal," or "over time" (among others), whereas formal definitions in our literature are presented within certain contexts. Wang (2016) defines a dynamic *model* as a "representation of a system that evolves over time. In particular it describes how the system evolves from a given state at time *t* to another state at time $t + 1$ as governed by the transition rules and potential external inputs" (p. 242). @vancouver_translating_2018 state that dynamic *variables* "behave as if they have memory; that is, their value at any one time depends somewhat on their previous value" (p. 604). Finally, @monge_theoretical_1990 suggests that in dynamic *analyses*, "it is essential to know how variables depend upon their own past history" (p. 409). 

The crucial notion to take from dynamics, then, is that the past matters and future states are constrained by where they were at prior points in time [@boulding1955defense; @flytzanis1976linear; @simon1991architecture; @petris2010r]. Below, we unpack a number of important principles couched in this simple idea.
