---
output: pdf_document
---

# Discussion - A Dynamic Perspective

We opened this paper by discussing how researchers are beginning to approach dynamics. We pointed to two frameworks -- growth and relationships -- as examples of empirical research doing the hard work of getting our thinking beyond static, cross-sectional associations. They were appropriate first steps toward dynamics given our field's history with random coefficient models and more recent emphasis on growth curve modeling, but there are many dynamic principles outside the context of a specific longitudinal model -- we presented them here. Taking a dynamic perspective means focusing on memory, constraints, timescales, reciprocal influence, initial conditions, and exploring an array of satistical properties like serial correlation and stationarity. Taking a dynamic perspective means being seriously concerned that your trajectory is not simply a random walk or white noise process.

We close this paper with three short, unique sections to solidify the principles and what we mean by a dynamic perspective. In the first section we highlight recent dynamic studies that explore some of the principles discussed here. Then, we consider what dynamics is not. We conclude by presenting the linear dynamic systems model as the fundamental framework for dynamic investigations. 

## Recent Work

There are several great studies already exploring some of the key dynamic properties. To get a sense for this literature and to highlight the principles that they capture we searched for empirical studies that were (1) published in the last five years (2) in the *Journal of Management*, *Journal of Applied Psychology*, or *Academy of Management Journal* and (3) contained "dynamic" or "dynamics" in the title. We exclude research that is cross-sectional, ethnographic, or focuses only on growth/covariates of growth. The articles and the dynamic notions that they emphasize are listed in Table one.

The studies as a whole explore a number of dynamic principles. First, every study emphasizes lags -- they evaluate associations, influence, and patterns from current states to subsequent states, or prior states to current states. For example, @hardy_interrelationships_2018 examine the relationship between self-efficacy and subsequent exploratory behavior, the relationship between prior exploratory behavior and subsequent metacognition, and the relationship between self-efficacy and subsequent exploratory behavior (among others). @jones_baby_2016 study the relationship between revealing behaviors among pregnant women and subsequent physical health symptoms. Many also discuss serial correlation, autocorrelation, or autoregression. @gabriel_emotional_2015 assess autocorrelations ranging from T-1 to T-20 seconds, and their Table one demonstrates how autocorrelation coefficients for emotion decrease in size over longer lags (i.e., emotions show stronger self-similarity when they are related to $t-1$ emotions versus $t-20$ emotions). Finally, a number of studies explore reciprocal patterns over time and a few discuss unobserved heterogeneity indirectly by using a statistical test to determine if they should employ a fixed or random effects model (i.e., a Hausman test). These are recent, exciting dynamic perspectives that our literature is beginning to expose. 

Notice, however, that we also include an "opportunities" column in Table one that highlights the principles that could be examined with the data that currently exist but are not discussed in each article. Although researchers are thinking about lags and autocorrelation, there are other principles like initial conditions, equilibrium, timescales, random walks, stationarity, and endogeneity that have yet to be explored and are great opportunities to discover even more dynamics. We also noticed that many of the studies that assess autocorrelation do not have conceptual discussions about memory or self-similarity or constraints, but instead assess autocorrelation as a statistical hurdle to overcome before discussing the lag relationship of interest. It is certainly appropriate to assess -- especially to avoid inferential errors -- but we would like to reiterate that finding evidence of memory in a state is useful knowledge on its own and helps build theoretical understanding. 

\begin{center}

---------------

Insert Table 1 Here

---------------

\end{center}

Finally, many of the principles that we highlight as opportunities do not require grueling extra work. Rather, they can be examined with the data that already exist to (a) learn more about the system and (b) deter inferential errors. We hope this paper will ignite more study into the principles we described. 

## What Dynamics Is Not

During a time when authors were discussing what constitues theory, @sutton1995theory produced a useful article describing what theory is not -- it is a conerstone reading for management, organizational behavior, human resources, and organizational psychology programs across the country. A similar approach may be useful here, where addressing what dynamics is not could help researchers fully grasp its content. 

### Time as a predictor is not dynamics.

Our field has a number of great papers discussing the idea that time cannot be causal. Ployhart and colleagues have probably said it best: "constructs do not change, evolve, or develop because of time; rather they do so over time. For example, time does not cause children to grow into adults. Even though time is highly related to physical growth, the causes of growth are genetics and environment" [@ployhart_longitudinal_2010, p. 98]. Moreover, our theories do not specify time as a causal variable but instead specify that changes will happen over time due to other causes [@pitariu_explaining_2010].

We agree with these statements but extend them slightly to encompass a dynamic perspective. Imagine a study that evokes time as a moderator and then makes a conclusion like, "early on A happens, whereas later on B happens." They do not discuss time as the cause, but they do argue that they are studying dynamics because state behaviors differ at time 3 compared to time 2. Identifying that time 3 states and relationship patterns are different from those at time 2 is useful, but it is not dynamics, it is not characterizing how past behavior constrains new state patterns or how states from one moment reach others at subsequent moments. In concrete terms, finding that job satisfaction is high for newcomers and low for old-timers is not dynamics, neither is recognizing that it positively relates to performance during week one but negatively relates to performance after a month on the job. Dynamics is studying how job satisfaction unfolds through time based on its constraints, self-similarity, initial conditions, and reciprocal sources of influence. 

### Static relationships across time are not dynamics.

Longitudinal data do not automatically make the focus of a study dynamics. Many studies that collect longitudinal data examine static relationships across time rather than dynamics, and to see this consider two simple (mock) examples of studies on burnout and job satisfaction. 

The first study collects self reports of burnout and job satisfaction everyday for three weeks. The researchers regress burnout at time $t$ on satisfaction on time $t$ and report the relationship. Their analysis, therefore, considers the following relationship:

\begin{equation}
\textrm{Satisfaction}_{t} = a * \textrm{Burnout}_{t} + e_{t}
\end{equation}

\noindent where satisfaction at time 1 is related to burnout at time 1, satisfaction at time 2 is related to burnout at time 2, and so on.

Now consider a slight change. The researchers instead examine self-similarity in satisfaction and a lag effect from burnout. That is:

\begin{equation}
\textrm{Satisfaction}_{t} = a * \textrm{Satisfaction}_{t - 1} + b * \textrm{Burnout}_{t - 1} + e_{t}
\end{equation}

\noindent where satisfaction at time 5 is related to its prior self and burnout at time 4, satisfaction at time 6 is related to satisfaction and burnout at time 5, and so on. 

The only difference between the aforementioned studies is that one acknowledges memory and lags whereas the other does not, but those aspects represent and imply fundamentally different things about the world. The first (equation 15) considers the world as a sequence of cross-sectional slices, a perspective that @ilgen_computational_2000 call "multiple snapshots," where static associations are compiled across time. It also implies that any state behaviors or relationships among the states follow a seemingly odd sequence: relationships happen at one moment and then are wiped out and replaced by completely new behavior and relationship patterns at the next. Finally, it represents a world where burnout instantaneously causes satisfaction. Virtually all studies that use a time-varying covariates model adopt this perspective.

The second, dynamic perspective (equation 16) represents a much different structure. Satisfaction is constrained by where it was in the past and therefore it cannot bounce to extreme levels without first moving from its prior state. Moreover, the effect from burnout takes time to occur and aligns with intuitive and theoretical notions of causality. Finally, the patterns between satisfaction and burnout will ultimately drive toward equilibrium. A study of relationships over time is useful, but it is not dynamics.

### Dynamics is not synonymous with growth.

A dynamic phenomenon does not have to grow or exhibit increasing/decreasing trend. The underlying dynamics may or may not produce trend, but growth is not a fundamental concept in dynamics. Similarly, observing growth or correlates of growth in an empirical study is not dynamics. It is useful and we hope researchers continue to explore growth patterns in their content areas, but a study that "unpacks dynamics" is much different from a study that estimates trend and predictors of trend. 

## Conclusion - The Linear Dynamic Systems Model

Much of the historical research in our field emphasized bivariate, cross-sectional relationships that are embodied in the general linear model. As we incorporate dynamics there are a number of additional principles to consider, and we discussed many of them in this paper. The principles of dynamics are all represented in a different fundamental model: the linear dynamic systems model. Just as the general linear model subsumes historical research focused on static relationships, the linear dynamic systems model will embody our upcoming dynamic investigations. In its simplest form, the linear dynamic sytems model is:

\begin{equation}
\textbf{x}_t = \textbf{A} \textbf{x}_{t-1} + \textbf{b}
\end{equation}

\noindent where **x**$_t$ is a vector of states at time $t$. The vector is just like the state vector we presented in the concepts section (depletion, fatigue, burnout), but we are using a generic term to capture any state or set of states of interest. The equation also captures the states at the prior time point **x**$_{t-1}$, and those states are multiplied by **A**, a matrix of transition weights. The transition weights capture memory, constraints, lags, and reciprocal influence within the system -- the diagonal elements represent self-similarity and the off-diagonal elements are cross-state influence. **b** is a vector of constant values (time-invariant) that are commonly referred to as forcing terms. Although they do not receive a term in the equation, initial conditions are also inherent to the linear dynamic systems model because specifying or identifying a trajectory requires starting values. The principles described in this paper are embodied in the linear dynamic systems model, and it will serve as the underlying model as we enter the exciting domain of dynamics. 

```{r, echo = F}
library(xtable)
library(knitr)
library(kableExtra)
library(tidyverse)




highlight_df <- data.frame(
 "A" = c("Berrone, Gelabert, Massa-Saluzzo, and Rousseau, 2016",
	       "Call, Nyberg, Ployhart, and Weekley, 2015",
	       "Drescher, Korsgaard, Welpe, Picot, and Wigand, 2014",
	       "Gabriel and Diefendorff, 2015",
	       "Hardy, Day, and Steele, 2018",
	       "Jones, King, Gilrane, McCausland, Cortina, and Grimm, 2013",
	       "Taylor, Bedeian, Cole, and Zhang, 2014",
	       "Tepper, Dimotakis, Lambert, Koopman, Matta, Park, and Goo, 2018"),
 
 "D" = c(linebreak("Unobserved heterogeneity\nLags"),
	       linebreak("Unobserved heterogeneity\nLags\nSerial correlation\nTimescales"),
	       linebreak("Lags\nAutocorrelation"),
	       linebreak("Lags\nAutocorrelation\nReciprocal relationships\nTimescales"),
	       linebreak("Lags\nReciprocal relationships"),
	       linebreak("Lags\nAutocorrelation\nReciprocal relationships"),
	       linebreak("Lags\nAutocorrelation\nReciprocal relationships"),
	       linebreak("Lags\nAutoregression")),
 
 "C" = c(linebreak("Initial conditions\nMemory\nTimescales\nBoundary conditions\nReciprocal relationships\nEquilibrium\nRandom walks and white noise\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nBoundary conditions\nReciprocal relationships\nEquilibrium\nRandom walks and white noise\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nTimescales\nBoundary conditions\nReciprocal relationships\nEquilibrium\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nBoundary conditions\nEquilibrium\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nMemory\nTimescales\nBoundary conditions\nEquilibrium\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nTimescales\nBoundary conditions\nEquilibrium\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nTimescales\nBoundary conditions\nEquilibrium\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity"),
	       linebreak("Initial conditions\nTimescales\nBoundary conditions\nEquilibrium\nReciprocal relationships\nRandom walks and white noise\nUnobserved heterogeneity\nStationarity\nEndogeneity")))





names(highlight_df) <- c("Article", "Dynamic Notions", "Opportunities")


highlight_df %>%
  kable('latex', booktabs = T, escape = F, align = 'l', longtable = T, caption = '\\label{highlight}Recent studies exploring dynamic notions.') %>%
  kable_styling(latex_options = c("repeat_header")) %>%
    column_spec(1, width = '10em') %>%
    column_spec(2, width = '11em') %>%
    column_spec(3, width = '20em') %>%
  row_spec(1:8, font_size = 12) %>%
  row_spec(1:7, hline_after = T)
```
