---
output: pdf_document
---

# Stepping Toward Dynamics -- Growth

One of the first steps our field is taking toward dynamic thinking is by examining whether something goes up or down over time -- examining trend or growth patterns. 

@hulsheger_dawn_2016 explores fatigue trends. He motivates his study by stating that his examination of the "the continuous ebb and flow of fatigue over the course of the day and about the factors that influence this temporal ebb and flow" responds to calls to "empirically address the dynamic process of recovery and thereby helps refine recovery theory" (p. 906). For 5 consecutive workdays he assesses fatigue with self-report surveys -- one in the morning, another at the first work break, a third at the end of work, and the last in the evening -- among a sample of Dutch employees. All surveys measure fatigue, and the morning survey also assessses sleep quality whereas the fourth measures psychological detachment. He estimates fatigue growth curves and correlates sleep quality and psychological detachment with both the fatigue intercept and slope, respectively. 

@dunford_is_2012 examine burnout trajectories over two years. They motivate their study by stating that, "theoretically, much of the burnout literature suggests that burnout should be progressive and dynamic, yet most empirical research has focused on explaining and testing the antecedents of static levels of burnout," therefore "knowing for whom burnout changes and when this pattern of change occurs leads to a more realistic view of the dynamism of human experience and better managerial prescriptions for addressing burnout" (p. 637). Over two years they assess healthcare workers with five measurements, each separated by six months. All surveys measure burnout (all dimensions), and the researchers also collect between person assessments of job transitions (a categorical variable indicating whether an employee is a newcomer, recently underwent an internal job change, or remained at the same position throughout). They estimate a sequence of growth curves and examine linear and quadratic slope terms for all three burnout dimensions. They also covary job transition type with the intercept and slope terms. 

## Summary

These authors are clearly interested in dynamics and in this framework they examine whether trajectories exhibit trends (growth), between person differences in trend, and correlate other variables with those trends. 