---
output: pdf_document
---

Think about how common it is to find phrases about dynamics scattered throughout an introduction to an article, phrases like "we are going to address the dynamics," "taking a dynamic perspective," "prior research has not appreciated the dynamics," "we consider the phenomenon as dynamic," or "we examine it on a dynamic basis." What do these mean? How do researchers take a dynamic perspective?

Dynamics refers to a specific branch of mathematics/mechanics where the fundamental concept is that the past constrains future behavior  [@boulding1955defense; @flytzanis1976linear; @simon1991architecture]. Researchers tend to study dynamics, however, with respect to a statistical model or class of models. For example, researchers that are familiar with growth models will talk about the importance of growth in a variable or how within-person trajectories have been ignored in prior research, they will then estimate a growth curve and ultimately convey something about trend or growth over time and how this result has added a new dynamic perspective to our understanding [e.g., @dunford_is_2012; @hulsheger_dawn_2016]. "Growth model thinking," as well as other recent ways of discussing phenomena over time, have produced wonderful insights into important processes in organizational science, and we see them as initial steps toward dynamics. Ultimately, though, they miss many fundamental principles of dynamics. 

When researchers couch their thinking in a particular model some concepts naturally go unnoticed. Our field is accumulating tremendous knowledge by collecting longitudinal data, focusing on how things happen over time, and opening the door of dynamics, but there are dynamic principles that have yet to be exposed in our literature -- researchers have not yet stepped fully through the door. In this paper, we discuss a variety of dynamics principles; some are concepts that will reorient how researchers think about dynamics and others are statistical properties that, if ignored, result in biased inferences. Ultimately we are bringing attention to principles that should be incorporated if researchers are interested in a dynamic perspective.

Through this endeavor, we make three specific contributions. First, we explicitly define dynamic principles to build consensus on what researchers should be expected to discuss and assess when they argue that they "address the dynamics" or "take a dynamic perspective." We move the field from an unorganized, small set of ideas couched in particular statistical models to a fundamental set of principles that will help researchers understand and communicate dynamics. Second, we reduce the gap some researchers may feel due to their interest in dynamics but limited exposure to mathematics in their graduate training. By finding a middle ground between overwhelming mathematics at one extreme and an informal, abstract and useless glossing over of concepts at the other, we hope to gently guide researchers to a more formal understanding of dynamic principles. Finally, we highlight opportunities that researchers can take to appreciate dynamics with data that exist already -- in many cases, the jump to dynamic thinking does not necessarily require an entirely new data set.

Below, we first discuss two broad classes of "thinking with respect to a statistical model" that have done much of the hard work -- they are sets of empirical studies taking initial steps towards dynamics. The first we call "growth," and the second "relationships," and we discuss example studies in each to briefly show our field's interest in dynamics and how researchers approach it. These first two sections are not exhaustive, we are simply sampling the common ways researchers currently think about dynamics to motivate the core of the paper. There, we unpack the principles of dynamics. 
