---
output: pdf_document
---

# Stepping Toward Dynamics -- Relationships

Another popular approach is to examine relationships across time rather than trends or covariates of trend.

@gabriel_helping_2018 study the association among helping acts, depletion, and self-serving political acts. They motivate their study by highlighting the limitations of between-person research and then stating that "a more appropriate empirical test of this process requires an intraindividual lens that allows researchers to consider how OCBs, resources, and subsequent behaviors vary daily. That is, not assessing the dynamic relations between helping behaviors and related constructs potentially misaligns the theoretical underpinnings of the construct and the level of analysis used to assess their relationships (i.e., taking dynamic processes and assessing them with static, 'in general' assessments of constructs; Klein & Kozlowski, 2000)" (p. 2). For ten work days they collect surveys twice a day (morning and afternoon). Both the morning and afternoon surveys assess helping acts, depletion, and political acts. They regress afternoon depletion on afternoon helping acts and morning depletion. They regress afternoon political acts on afternoon depletion and morning political acts. They regress afternoon helping acts on afternoon depletion and morning helping acts.

@johnson_good_2014 study the relationship between justice behaviors, depletion, and OCBs -- they argue that exhibiting procedural justice behaviors is depleting and can negatively influence OCBs. They motivate their study by stating that our current justice knowledge comes from "cross-sectional studies examining between-person differences," but "there is a need for longitudinal, daily investigations of justice experiences that take a dynamic person-centric view" (p. 1). Ultimately they argue that their research design enabled them to "examine dynamic, within-person effects" and test a model "via a more granular approach to time" (p. 11). Their participants responded to surveys twice a day for 10 working days (morning and afternoon). The morning survey measured sleep quantity, whereas the afternoon survey measured justice behaviors, depletion, and OCBs. They regress afternoon depletion on the morning sleep quantity, the prior day's afternoon justice behavior, and the prior day's afternoon depletion. 

@rosen_who_2016 explore the relationship between incivility and self-control. They motivate their research by stating that "although examinations of incivility have gained momentum in organizational research, theory and empirical tests involving dynamic, within-person processes associated with this negative interpersonal behavior are limited" (p. 1). They also argue that "previous studies focused almost exclusively on chronic forms of incivility that occur on average during unspecified periods of time, which overlooks the dynamic and temporal nature of incivility and its effects. Consistent with ego depletion theory, we consider a dynamic process that explains why employees become more uncivil." (p. 2). Their participants respond to three surveys a day (morning, afternoon, and evening) for 10 workdays. The morning survey assesses self-control, the afternoon survey assesses self-control, experienced incivlity, and instigated incivility, and the evening survey measures experienced incivility and instigated incivility. They regress afternoon self-control on afternoon incivility and morning self-control. Another model regresses evening incivility on afternoon self-control.

@koopman_integrating_2016 examine the costs and benefits of OCBs on behalf of the actor -- specifically how OCBs relate to positive affect and work goal progress. They motivate their study by stating that they "respond to calls in the literature to examine the consequences of OCB on a more dynamic basis" (p. 415). Their respondents fill out three surveys (morning, afternoon, and evening) for ten workdays. The morning survey assesses OCBs, positive affect, and work goal progress. The afternoon survey measures work goal progress, and the evening survey assesses outcome variables irrelevant to the discussion here. They examine the relationship between OCBs and positive affect by regressing afternoon positive affect on morning OCB and morning work goal progress. They examine the relationship between OCBs and work goal progress by regressing afternoon work goal progress on morning OCB and morning work goal progress.

## Summary

These authors are also interested in dynamics. All test for within-person variance and motivate their studies by stating that "the good stuff" resides in the within-person relationships. They examine concurrent or lagged relationships across their variables over time, and they are able to collect many observations due to their frequent sampling.
