---
title: "intro_hype"
output: pdf_document
---


SHOULD WE SAY SOMETHING LIKE, THERE IS MORE TO PROCESS THAN MEDIATION?
How we got to now (six innovations).
"Johannes Gutenberg's printing press created a surge in demand for spectacles, as the new practice of reading made Europeans across the continent suddenly realize that they were farsighted; the market demand for spectacles encouraged a growing number of people to produce and experiment with lenses, which led to the invention of the microscope, which shortly thereafter enabled us to perceive that our bodies were made up of microscopic cells. You wouldn't think that printing technology would have anything to do with the expansion of our vision down to the cellular scale, just as you wouldn't have thought that the evolution of pollen would alter the design of a hummingbird's wing. But that is the way change happens." (4-5).
"This is an approach I have elsewhere called 'long zoom' history: the attempt to explain historical chnage by simultaneously examining multiple scales of experience -- from the vibrations of sound waves on the eardrum all the way out to mass political movements. It may be more intuitive to keep historical narratives on the scale of individuals or nations, but on some fundamental level, it is not accurate to remain between those boundaries. History happens on the level of atoms, the level of planetary climate change, and all the levels in between. If we are trying to get the story right, we need an interpretative approach that can do justice to all those different levels." (9). 


Life's other secret
"Science is not about devising hugely complex descriptions of the world. It is about devising descriptions that illuminate the world and make it comprehensible. The reason that Newton's law of gravity is important is not because it describes the meovement of every particle in the solar system. It is important because it opens up the possibility of simple models of the solar system that are comprehensible to human beings. Similarly, any kind of equation for life has to be comprehensible, as well as correspond to how organisms function -- on some level of description" (p. 9).

"There is no special kind of matter, no spart of life, that distinguishes the living from the nonliving...It now seems very clear that the difference between life and nonlife is one of organization, not of component parts....Car...car can move, but a collection of automobile parts cannot; what is the difference? It is how the parts are organized. Take the parts apart and the basic pieces are there -- but *motion* isn't...Which explanation makes more sense: one based on motion as an invisible and ineffable substance, or one in which it is a process that can occur only when the parts are suitably organized? Life is a process, not a substance." (p 10).

"...whether life differs fundamentally from inorganic matter and processes, or whether it is just a rather striking example of entirely normal inorganic processes that have gathered momentum, until their consequences have dominated the history of our planet. It is too easy to be overwhelmed by the amazing consequences of living processes and to imagine that the processes themselves must be amazing as their consequences" (p. 7).

"Genes are not the laws of life; they are what the laws use to operate. As a loose analogy, the current state of the solar system is determined by two things: the mathematical laws of motion, plus a list of initial conditions that tell us where all planets are at some chosen instant. Plug the initial conditions into the laws, and all of the intricacies of the solar system follow. There is a strong tendency to think of genes as constituting the laws of biological development, but that is not so; their role is much closer to that of initial conditions. In other words, genes are not the key to life. They are a key. There are other fundamental laws, mathematical rules into which the genetic code is plugged" (p. 25). 