---
# https://crsh.github.io/papaja_man/index.html

title             : "Principles for Describing or Explaining Process"
shorttitle        : "PROCESS PRINCIPLES"

author: 
  - name          : "..."
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "..."
    email         : "..."


affiliation:
  - id            : "1"
    institution   : "..."


author_note: |
  ....

abstract: |
  Begin here...
  
keywords          : "...."
wordcount         : "95"

bibliography      : ["references.bib"]

figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes

lang              : "english"
class             : "man"
output            : papaja::apa6_pdf
---

```{r load_packages, include = FALSE}
library("papaja")
```

```{r analysis_preferences}
# Seed for random number generation
set.seed(42)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'figs/',echo = FALSE, warning = FALSE, message = FALSE)
```


```{r child = 'pp_intro.Rmd'}
```

```{r child = 'pp_systems.Rmd'}

```

```{r child = 'pp_math.Rmd'}

```

```{r child = "pp_comp.Rmd"}

```

```{r child = "pp_discussion.Rmd"}

```



\newpage

# References
```{r create_references}
r_refs(file = "references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}