---
title: "intro"
output: pdf_document
---

We -- organizational psychologists -- are increasingly interested in process and dynamic phenomena. Longitudinal studies are becoming more prevalent in our literature and the number of time points they employ appears to be growing [@xu2018]. The empirical literature uses the term "dynamics" at expoentially larger rates in recent years [@deshon2012]. A majority of published methods literature now focuses on longitudinal data analysis [@aguinis2009], and there are now many great reviews on the conceptual and methodological issues related to process and dynamics [@wang2016; @beal2015; @shipp2015; @mitchell2001]. Moreover, this interest covers many content areas, including emotional labor [@bono2007; @beal2015; @gabriel2015], workplace stress and well-being [@ritter2016; @wang2014], organizatiional performance [@short2006], self-regulation [@hardy2018], newcomer adjustment [@kammeyer-meuller2013], justice and trust [@kaltianinen2017], leadership [@farh2018; @schaubroeck2016; @kalish2016], decision-making [@huang2012], team performance [@humphrey2017], counterproductive work behaviors [@meier2013], work-family conflict [@matthews2014], job satisfaction [@zablah2016], and team emergent states [@kozlowski2012]. In summary, explaining how a process functions appears to be of great interest to current organizational science. 

There are many ways to do so -- alternative representations that we might use when we want to describe sequences of events and their relationships. Just as different statistical models can be used to draw the same inference given the appropriate assumptions about the data generating process, we can use different forms of explanation to describe process. For example, Bandura [-@bandura] and Kuwabara et al. [-@kuwabara2018], respectively, explain self regulation and lay beliefs about networking with verbal theories, @denrell2009 presents a mathematical explanation of social impressions, and @vancouver2014 employ both mathematical and computational approaches to explain self-regulation. All of these authors use different techniques and forms of representation, but they are all trying to convey how the processes they study behave. 

In this paper, we present some of the fundamental principles researchers use to convey process. The principles come from a number of areas, including mathematics, systems theory, dynamics, and computational modeling, and they are all ways to represent and describe relationships over time at different levels of abstraction. For example, we could use a difference equation to explain the trajctory of one variable, or we could use terms like trend or cycles that describe the emergent behavior of the variable but through a different lens. What is important is that there are fundamental principles/concepts that go into to describing a process over time. Don't necessarily need to be causal; we can explain something and it can be causal or non causal. 

We provide several contributions in doing so. First, we believe our discussion will help researchers augment their current approach to explaining process. It can be helpful to be exposed to different approaches, provide ideas etc., and we hope our paper provides new ideas to seasoned researchers in this area. Second, although there is a substantial amount of literature on mathematical process principles and dynamics, it is sophisticated and technical. Much of this work is not easily accessible to researchers with the usual methodological and statistical background obtained from doctoral level training in OP/OB; we want to help distill it. Finally, we discuss ways to study process for researchers who may not want to want to develop sophisticated math or computational models. Some people claim that math is the only option. For example, Pearl (2009) states that any explanation "worthy of the title theory must be able to represent causal questions in some mathematical language" (p. 102). There is also some pressure to produce computational theories. For example, VANCOUVER COMP MODELS ARE BETTER; AND KOZLOWSKI COMP FRAMEWORKS ARE BETTER. But there are not many comp modelers in organizational psychology (vancouver orm); and the social sciences do not emphasize mathematics as much as some of the more physical sciences (vancouver orm). Moreoever, Renee Thom points out that sometimes qualitative representations produce more error than their quantitative counterparts but nonetheless are better clues to the underlying process. We do not claim that one approach is better or worse than another; we simply want to describe process principles from different domains to give researchers alternative ways of talking about, specifying, and representing process behavior. 

Below, we do these things. There are other excellent papers on aspects that we will not cover. Ployhart and Vandenberg discuss how to design and analyze a longitudinal study, Pitariu and Ployhart how to propose dynamic hypotheses, and Wang provides an overview of dynamic statistical models. In this paper, conversely, we focus solely on principles researchers use when they explain process.



after meeting

Here are all of the ways process is discussed. But they are talking about different things. Hollenbeck consensus building.

At what point in the reduction are you doing process? At what level of abstraction/reduction amd I explaining the process versus describing the emergent properties of the process?

Intro

There is increasing interest in process and dynamic phenomena in our science. For example

Some examples include. example 1. example 2. example 3 from different conetent areas doing different things.

All of the examples are interested in process, but notice that they are talking about different things. explain the differences. Which is an appropriate representation of process behavior?

The examples above were different forms of explanation from different content areas, now consider the same dilemma at different levels of abstraction. Weight gain. At what level of abstraction/reduction are we explaining the process versus describing the emergent properties of the process?

Our paper
Distinguish between explaining vs. describing process. 
Fundamentals for explaining process and fundamentals for describing process.
The many representations of process. Consensus build

# Begin

We -- organizational psychologists -- are increasingly interested in process and dynamic phenomena. Longitudinal studies are becoming more prevalent in our literature and the number of time points they employ appears to be growing [@xu2018]. The empirical literature uses the term "dynamics" at exponentially larger rates in recent years [@deshon2012]. A majority of published methods literature now focuses on longitudinal data analysis [@aguinis2009], and there are now many great reviews on the conceptual and methodological issues related to dynamic and within-person models [@wang2016; @beal2015; @shipp2015; @mitchell2001]. Moreover, this interest covers many content areas, including emotional labor [@bono2007; @beal2015; @gabriel2015], workplace stress and well-being [@ritter2016; @wang2014], organizatiional performance [@short2006], self-regulation [@hardy2018], newcomer adjustment [@kammeyer-meuller2013], justice and trust [@kaltianinen2017], leadership [@farh2018; @schaubroeck2016; @kalish2016], decision-making [@huang2012], team performance [@humphrey2017], counterproductive work behaviors [@meier2013], work-family conflict [@matthews2014], job satisfaction [@zablah2016], and team emergent states [@kozlowski2012]. In summary, explaining how a process functions appears to be of great interest to current organizational science. 

Consider a few examples. Example 1 process interest statement and then what their study describes/explains. Example 2 process interest statement and then what their study describes/explains. Example 3 process interest statement and then what their study describes/explains. 

All of the aforementioned examples are interested in process, but notice they they are talking about different things. ((Explain the differences)). Which is an appropriate representation of process behavior? This is a dilemma/problem that we do not seem to have consensus on. 

Here is another example to pinpoint the dilemma. Imagine that we are interested in weight gain among US males who are 50 years or older, and to investigate it we conduct three longitudinal studies. **Option A**. In the first, we find and report that the average male gains one pound every year for the rest of this life. In the second, we find and report a positive relationship between male weight and caloric intake across time, and suggest that caloric intake has an effect on weight. In the third, we propose that weight at any point in time is determined by its prior value and the difference between the number of consumed calories and the number of expended calories.

**Option B**. In the first, we model weight over time, find a significant, positive trend, and suggest that the average male gains one pound every year for the rest of his life. In the second, we model weight and the number of consumed calories over time, find a significant, positive relationship between them, and suggest an effect of caloric intake and weight. In the third, we model initial weight, weight, and the number of consumed and expended calories over time and suggest that weight is a function of prior weight and difference between caloric intake and expenditure.

Which of these is a process study? Where is the line between explaining the process versus describing its emergent properties?

In this paper, we try to build consensus around these issues. What do we mean by process? What are the different ways that we can represent it? We approach them in two parts.

In the first section we contrast process with other, "over time" concepts. There are loose and formal ways to use terms and notions about behavior over time, and we point out the differences to locate process within that concept map. We then provide a definition drawn from @vanden and @pettigrey. Although the term is used in a variety of ways in the literature -- including, for example, as a construct when something like "team process" is placed in a box with an arrow directed at "team performance" -- we present a definition that describes what researchers look for when they unpack that "team process" box. Finally, we distinguish explaining versus describing it. Both are valuable, but...

In the second section we then discuss principles for either 1) describing or 2) explaining process. The principles come from a number of areas, including mathematics, systems theory, dynamics, and computational modeling, and they are all ways to represent and describe relationships over time at different levels of abstraction. For example, we could use a difference equation to explain the trajectory of one variable, or we could use terms like trend or cycles that describe its emergent behavior but through a different lens. Both try to represent behavior over time, and we want to point out the fundamentals for how to do so. Moreover, some of the principles represent process in a helpful way that can be conveyed in an article,  What is important is that both represent process but with  entail principles to represent the process. We separate the principles as they relate to  there are fundamental principles behind boththat go into to either 1) describing or 2) explaining a process over time. These principles are also not necessarily always (non) causal.  

both: represent behavior over time. convey behavior over time
principles for how to do so
some are about describing observed data
some are about explaining data generation. 

Don't necessarily need to be causal; we can explain something and it can be causal or non causal. 

We provide several contributions in doing so. First, we believe our discussion will help researchers augment their current approach to explaining process. It can be helpful to be exposed to different approaches, provide ideas etc., and we hope our paper provides new ideas to seasoned researchers in this area. Second, although there is a substantial amount of literature on mathematical process principles and dynamics, it is sophisticated and technical. Much of this work is not easily accessible to researchers with the usual methodological and statistical background obtained from doctoral level training in OP/OB; we want to help distill it. Finally, we discuss ways to study process for researchers who may not want to want to develop sophisticated math or computational models. Some people claim that math is the only option. For example, Pearl (2009) states that any explanation "worthy of the title theory must be able to represent causal questions in some mathematical language" (p. 102). There is also some pressure to produce computational theories. For example, VANCOUVER COMP MODELS ARE BETTER; AND KOZLOWSKI COMP FRAMEWORKS ARE BETTER. But there are not many comp modelers in organizational psychology (vancouver orm); and the social sciences do not emphasize mathematics as much as some of the more physical sciences (vancouver orm). Moreoever, Renee Thom points out that sometimes qualitative representations produce more error than their quantitative counterparts but nonetheless are better clues to the underlying process. We do not claim that one approach is better or worse than another; we simply want to describe process principles from different domains to give researchers alternative ways of talking about, specifying, and representing process behavior. 
















There are parts to this paper: 1) clarify what process is and distinguish between explaining  versus describing it; 2) discuss principles and fundamentals for either explaining or describing process. 



Weight goes up over time. 

1)

Not a process

2)

A description of the emergent properties of a process.
There is a process at play that determines weight going up over time, and this is a description of the emergent stuff.

stocks and flows, trend, growth, granger causality

Are these:

1) descriptions of the emergent properties of a process

or

2) descriptions, but not process. We can only use the term process when we provide a mechanistic explanation. If this is the case, then what do we call the first set of principles (e.g., growth, periodicity, magnitude)...

or

3) it depends. Growth/trend/gc can be used to explain or describe the observed data



3) what are process descriptions then? Or, can we only use the term process when we provide a mechanistic explanation? 

    + So we therefore have no ""

* Not a process

  + This phrase has no meaning
  + Your representation




# What is process

Before jumping to a definition of process it is helpful to consider other, related concepts.

### Dynamics

Dynamics refers to a specific branch of mathematics, but the term is used in different ways throughout our literature. It is used informally to mean "change", "fluctuating," "volatile," "longitudinal," or "over time" (among others), whereas formal definitions in our literature are presented within certain contexts. Wang defines a dynamic *model* as a "representation of a system that evolves over time. In particular it describes how the system evolves from a given state at time *t* to another state at time *t + 1* as governed by the transition rules and potential external inputs" (p. 242). Vancouver states that dynamic *variables* "behave as if they have memory; that is, their value at any one time depends somewhat on their previous value" (p. 604). Finally, Monge suggests that in dynamic *analyses*, "it is essential to know how variables depend upon their own past history" (p. 409). 

The crucial notion to take from dynamics, then, is memory. When the past matters, and future states are constrained by where they were at prior points in time, dynamics are at play.

### Longitudinal

Longitudinal is a broad term that is usually paired with one additional term to refer to an investigation's method, data, or aim. A study that uses a longitudinal *method* is different from a cross-sectional design due to the number of observations, such that longitudinal designs employ repeated observations, whereas cross-sectional studies do not. Longitudinal *data* are repeated observations on multiple units, whereas panel data or time series are repeated observations on one unit -- and are the most common data structure in economics. 

The other distinction surrounding longitudinal studies is what they can be used for -- what their aim is. Ployhart and Vandenberg state that "longitudinal research emphasizes the study of change and contains at minimum three repeated observations on at least one of the substantive constructs of interest" (p. 97). Similarly, Baltes and Nesselroade note, "the study of phenomena in their time-related constancy and change is the aim of a longitudinal methodology" (p ?). Both of these definitions reveal the recent tendency to focus on change in longitudinal studies. For example, a longitudinal investigation could observe increasing or decreasing trajectories (or other forms of change) across time. This change emphasis is likely due to the increasing knowledge and application of growth models, where the concept of modeling change has received lots of attention [@baltes]. 

### Process

We presented the notions above to help pinpoint what process refers to. Dynamics refers to systems with memory, where current states are driven to future states by transition rules and external inputs. Longitudinal studies collect data on multiple units across time, and some suggest that they ought to emphasize change. Process is about sequences of events with or without memory and with or without change. Pettigrey (1997) provides a formal definition: process is "a sequence of individual and collective events, actions, and activities unfolding over time in context" (p. 2). 

Similar to roberts and hulin (teams week 1 1978 with rousseau). "Most research in our field is static. Most studies are fleeting glances (analogous to stop-action photographs) at organizations" (70). "They fail to indicate the ordered sequence of events...Frozen moments do not capture...a process, nor do statistical interactions make a sequence" (71). 

# Explanations versus Descriptions

Introduce as a lead in to below. Below, we present fundamentals for describing process, and fundamentals for explaining process. 

# On Modeling

A theory is an explanation, a model is an instantiation of that theory.

* Do you use models in explanations? Yes and No.

  + No in the sense that theory is the explanation. 
  + Yes in the sense that theories do not explain everything, they are "instantiations of the real world."
  
* Do you use models in description? Yes and No.

  + No when I just describe what I see in the data.
  + Yes when I evoke a statistical, computational, or any other type of model.
  

