---
title: "intro"
output: pdf_document
---

We -- organizational psychologists -- are increasingly interested in process and dynamic phenomena. Longitudinal studies are becoming more prevalent in our literature and the number of time points they employ appears to be growing [@xu2018]. The empirical literature uses the term "dynamics" at exponentially larger rates in recent years [@deshon2012]. A majority of published methods literature now focuses on longitudinal data analysis [@aguinis2009], and there are now many great reviews on the conceptual and methodological issues related to dynamic and within-person models [@wang2016; @beal2015; @shipp2015; @mitchell2001]. Moreover, this interest covers many content areas, including self-regulation [@hardy2018], leadership [@schaubroeck201], and team performance [@humphrey2017], among others.

Given our interest in "process" phenomena, what distinguishes a process from a non-process study? What are some fundamentals for people wanting to study process? Consider the following set of studies and, while reading, ask yourself which you feel appropriately represents process. Imagine that we are interested in weight gain among US males who are 50 years or older, and to investigate it we conduct three longitudinal studies. **Option A**. In the first, we find and report that the average male gains one pound every year for the rest of this life. In the second, we find and report a positive relationship between male weight and caloric intake across time, and suggest that caloric intake has an effect on weight. In the third, we propose that weight at any point in time is determined by its prior value and the difference between the number of consumed calories and the number of expended calories.

**Option B**. In the first, we model weight over time, find a significant, positive trend, and suggest that the average male gains one pound every year for the rest of his life. In the second, we model weight and the number of consumed calories over time, find a significant, positive relationship between them, and suggest an effect of caloric intake and weight. In the third, we model initial weight, weight, and the number of consumed and expended calories over time and suggest that weight is a function of prior weight and difference between caloric intake and expenditure.

Which of these is a process study? Where is the line between explaining a process versus describing its manifest properties? In this paper, we try to build consensus around these issues. What do we mean by process? And what are the different ways that we can represent it? We approach these questions in two parts.

In the first section we contrast process with other, "over time" concepts. There are loose and formal ways to use terms and notions about behavior over time, and we point out the differences to locate process within that concept map. We then provide a definition drawn from @vanden and @pettigrey. Although the term is used in a variety of ways in the literature -- including, for example, as a construct when something like "team process" is placed in a box with an arrow directed at "team performance" -- we present a definition that describes what researchers actually look for when they unpack that "team process" box. We also discuss the difference between explaining versus describing a process. Both are valuable, but researchers should be aware of how they differ.

In the second section we then discuss principles for either 1) describing or 2) explaining process. The principles come from a number of areas, including mathematics, systems theory, dynamics, and computational modeling, and they are all ways to represent and describe relationships over time at different levels of abstraction. For example, we could use a difference equation to explain the trajectory of one variable, or we could use terms like trend or cycles that describe its manifest behavior but through a different lens. What is important is that each is a way to represent a variable/behavior over time and we want to point researchers to principles that they can use to help them do so -- regardless of whether they are truly causal or non causal explanations.

(**Not clean paragraph** - may not even need it). We provide several contributions in doing so. First, we believe our discussion will help researchers augment their current approach to explaining process. It can be helpful to be exposed to different approaches, provide ideas etc., and we hope our paper provides new ideas to seasoned researchers in this area. Second, although there is a substantial amount of literature on mathematical process principles and dynamics, it is sophisticated and technical. Much of this work is not easily accessible to researchers with the usual methodological and statistical background obtained from doctoral level training in OP/OB; we want to help distill it. Finally, we discuss ways to study process for researchers who may not want to want to develop sophisticated math or computational models. Some people claim that math is the only option. For example, Pearl (2009) states that any explanation "worthy of the title theory must be able to represent causal questions in some mathematical language" (p. 102). There is also some pressure to produce computational theories. For example, VANCOUVER COMP MODELS ARE BETTER; AND KOZLOWSKI COMP FRAMEWORKS ARE BETTER. But there are not many comp modelers in organizational psychology (vancouver orm); and the social sciences do not emphasize mathematics as much as some of the more physical sciences (vancouver orm). Moreoever, Renee Thom points out that sometimes qualitative representations produce more error than their quantitative counterparts but nonetheless are better clues to the underlying process. We do not claim that one approach is better or worse than another; we simply want to describe process principles from different domains to give researchers alternative ways of talking about, specifying, and representing process behavior. 

# Process

Before jumping to a definition of process it is helpful to consider other, related concepts.

### Dynamics

Dynamics refers to a specific branch of mathematics/mechanics, but the term is used in different ways throughout our literature. It is used informally to mean "change", "fluctuating," "volatile," "longitudinal," or "over time" (among others), whereas formal definitions in our literature are presented within certain contexts. Wang defines a dynamic *model* as a "representation of a system that evolves over time. In particular it describes how the system evolves from a given state at time *t* to another state at time *t + 1* as governed by the transition rules and potential external inputs" (p. 242). Vancouver states that dynamic *variables* "behave as if they have memory; that is, their value at any one time depends somewhat on their previous value" (p. 604). Finally, Monge suggests that in dynamic *analyses*, "it is essential to know how variables depend upon their own past history" (p. 409). 

The crucial notion to take from dynamics, then, is memory. When the past matters, and future states are constrained by where they were at prior points in time, dynamics are at play.

### Longitudinal

Longitudinal is a broad term that is usually paired with one additional term to refer to an investigation's method, data, or aim. A study that uses a longitudinal *method* is different from a cross-sectional design due to the number of observations, such that longitudinal designs employ repeated observations, whereas cross-sectional studies do not. Longitudinal *data* are repeated observations on multiple units, whereas panel data or time series are repeated observations on one unit -- time series are common in economics. 

The other distinction surrounding longitudinal studies is what they can be used for -- what their aim is. Ployhart and Vandenberg state that "longitudinal research emphasizes the study of change and contains at minimum three repeated observations on at least one of the substantive constructs of interest" (p. 97). Similarly, Baltes and Nesselroade note, "the study of phenomena in their time-related constancy and change is the aim of a longitudinal methodology" (p ?). Both of these definitions reveal the recent tendency to focus on change in longitudinal studies. For example, a longitudinal investigation could observe increasing or decreasing trajectories (or other forms of change) across time. This change emphasis is likely due to the increasing knowledge and application of growth models, where the concept of modeling change has received lots of attention [@baltes]. 

### Process

We presented the notions above to help pinpoint what process refers to. Dynamics systems have memory, where current states are driven to future states by transition rules and external inputs. Longitudinal studies collect data on multiple units across time, and some suggest that they ought to emphasize change. Process is about sequences of events with or without memory and with or without change. Pettigrey (1997) provides a formal definition: process is "a sequence of individual and collective events, actions, and activities unfolding over time in context" (p. 2). 

This definition is consistent with sentiments found in @hulinhubert1978 and @hulincompmodel. In these sources, the authors indirectly define process by describing their dissatisfaction with static research. They compare (some) OP/OB research to individual snapshots of behavior that -- even if compiled and aggregated to form a longitudinal study -- only reveal fleeting glances of the flow of the system. "Frozen moments do not capture...a process, nor do statistical interactions make a sequence" (71). Process, then, seems to entail sequences of events that, as stated above, must be couched in context.

Another point we want to reiterate is how words like "dynamics," "change," and "process" tend to be coupled. It is common to pair two or more of these terms with a phrase like "the dynamic process." But each of these words has a precise meaning. Dynamics is used for systems or variables with memory. Growth describes the systematic increase or decrease of a variable or system over time. Change has been used in two ways. It is sometimes used synonymously with growth: systematic increase or decrease. At other times, researchers partial prior observations of their dependent variable and in a regression model to emphasize the effect of an IV on the change in the DV. In this second way, change means "how this variable is different from the last point in time." 

Process is distinct from each of these terms, and it does not need to be paired with any. Processes can grow, or they can not grow; they can change or not change; they can contain dynamics or no dynamics. Stated differently, "no change" in not synonymous with "not process." There is still process to be found in behavior that does not change over time. 

Having discussed the differences between terms like process, longitudinal, and dynamics, we now unpack the principles. All of these are ways to represent process behavior -- to talk about how things unfold over time. Some are explanatory, whereas others simply describe the manifest behavior of the undiscovered true underlying mechanism, but all help convey process behavior. (**Do I need more on explanation vs. description?**)


