---
title: "princ_comp"
output: pdf_document
---

# Computational Principles

Above, we described and explained behavior over time by using representations most people are familiar with: verbal descriptions, plots, and math. There has recently been a push to comp model. These people are trying to do the same thing, but represent their process in a computer. 

Think of it this way. Above, we represented process on graphs, through equations, and through terms. To do so required certain principles. When we want to describe something in a computer language we also need certain principles: certain requirements or fundamentals about how we explain the process. 

Vancouver has pointed out some of these. He framed them as difficult pieces to putting stuff into code.

## Key States

What are the important states? A variable is an entity that can take different values at one point in time. A state is a variable that fluctuates over time. In information technology and computer science, a program is described as stateful if it is designed to remember preceding events or user interactions; the remembered information is called the state of the system.

We can also talk about the global state of the system as a whole -- its cumulative form. The state of the *system* describes enough about the system to determine its future behavior in the absence of any external forces affecting the system. The set of possible combinations of state variables is called the state space of a system.

## State Dynamics

## Constants

Values that do not change over time. Usually constants occur in the coefficients, or the weights. Vancouver's comp model 2018 included a weight relating assigned goal difficulty and goal specificity to self-efficacy that did not change over time.  

## Actions

## Action selection

## Context/Environment

How is the process situated? Simon's mouse behavior environment. He defines the context in which it can move around. Things happen with respect to the environment. 

## Noise

Is there error in the system, if so, where?

## Time Scale

How long does the process operate for? How many iterations does my for loop go for?

## Example: Simon 1956

### key states:

* hunger and thirst
* It is easier to think of these as stocks: food and water.

### State dynamics:

* The body requires energy, so the food and water stocks decrease over time (i.e., hunger and thirst increase)

### Actions

* these actions satisfy the state dynamics

    + resting, exploration, goal striving

### Action selection

* If the food and water stocks are above threshold, the agent rests
* When the stock of any need dips below threshold, the agent explores

* During exploration
    + agent randomly runs into objects. If they encounter a single object relevant to one of the needs, the agent acquires it
    + If the agent encounters two or more need-relevant objects, they evoke a simple ratio to make a decision 
        * compare energy required to meet the need (M) to the storage capacity with respect to the need (S)
        * or the effort required to get the object to how large the stock for this need is. Super large stocks take precedence
        
### Environment

* a space with goals within which the entity moves
* the individual is located in an environment that contains spatially distributed goal-relevant objects such as sources of food and water (239).
* the size of the food and water stocks are determined by the availability of the resources in the environment. Water is easier to come by than food and so food storage requirements are greater. Similarly, breathable air is easier to obtain than water and so its storage requirements are less than both food and water (239). 

## Summary


